### PR TITLE
Pattern folders are shown as overview table

### PR DESCRIPTION
**Pull request by opatut**
When selecting a pattern folder in the navigation, a table with its contents (subfolders & patterns) and some metadata (version, links to pattern & fullscreen demo) is shown, instead of a list of all patterns in their iframes. 

This reduces load time a lot (no request to the server, no complete rendering of _all_ included patterns) and is generally more clean. 

The feature can be enabled/disabled via `patternplate-client.ui.useFolderTable`, which is off (`false`) by default to keep the previous behaviour.

### CODE REVIEW

**Comment by marionebl** [comment]
Please provide a description of the changes.

**Comment by opatut** [comment]
I provide a description in the original post now.

**Comment by marionebl** [comment]
Please check the layout of the table on viewports with a width of `< 460px` and `500px`

**Comment by opatut** [comment]
Please review. It's not perfect (horizontal scrolling behind the navigation is broken, but that should be fixed independent of this), but much better now.

**Pull request merged**
